### PR TITLE
修复RegistryCoreOpsResource关流量

### LINKED ISSUE #226: [bugfix]RegistryCoreOpsResource quit server
### Describe the bug

6.1.4迭代中RegistryCoreOpsResource修改了/server/group/quit/{ip}，meta发布到6.1.4版本后，data,session发布时关流量仍然执行老的url，导致关流量调用报错。

### Environment

- SOFARegistry version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by bjxiaojian**
### Motivation:

6.1.4迭代中RegistryCoreOpsResource修改了/server/group/quit/{ip}，meta发布到6.1.4版本后，data,session发布时关流量仍然执行老的url，导致关流量调用报错。

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #226 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

File: server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/resource/RegistryCoreOpsResource.java [hunk 1]
```diff
@@ -45,97 +45,29 @@ public class RegistryCoreOpsResource {
...
-      return success
-          ? GenericResponse.buildSuccessResponse()
-          : GenericResponse.buildFailedResponse("kickoffServer: " + ip + " fail.");
-    } catch (Throwable th) {
-      LOGGER.error("[kickoffServer]", th);
-      return GenericResponse.buildFailedResponse(th.getMessage());
-    } finally {
-      LOGGER.info("[kickoffServer][end] server [{}]", ip);
-    }
+    return GenericResponse.buildSuccessResponse();
```
Comment (dzdx) [inline server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/resource/RegistryCoreOpsResource.java:58]: 带上 deprecated 的log和return

**Comment by dzdx** [comment]
commit message 修复一下，可以有一个是单独改version

**Comment by dzdx** [comment]
少改一个VERSION 文件？
